### ISSUE TITLE
Preparing for ESLint 10

### ISSUE THREAD

**Issue by SukkaW** [un-ts/eslint-plugin-import-x#438]
https://eslint.org/blog/2025/10/whats-coming-in-eslint-10.0.0/

ESLint 10 is coming soon, and we might wanna prepare `eslint-plugin-import-x` for ESLint 10.

Notably:

- `context.parserPath` will be removed, and there will be no replacement, which means we can no longer rely on `context.parserPath` to automatically determine the parser to use.
  - https://github.com/un-ts/eslint-plugin-import-x/blob/a3aae6179f0a3417b46066dfe59b388865d1a2eb/src/utils/parse.ts#L203
- `eslint/use-at-your-own-risk` and `FileEnumerator` will be removed, and there will be no replacement.
  - `import-x/no-unused-modules` will no longer work.

**Comment by MirKml** [comment]
just notice - [eslint 10 was released](https://eslint.org/blog/2026/02/eslint-v10.0.0-released/) 3 days ago

**Comment by melroy89** [comment]
yup... 

```
├─┬ eslint-plugin-import-x 4.16.1
│ └── ✕ unmet peer eslint@"^8.57.0 || ^9.0.0": found 10.0.0
├─┬ typescript-eslint 8.55.0
│ ├── ✕ unmet peer eslint@"^8.57.0 || ^9.0.0": found 10.0.0
│ ├─┬ @typescript-eslint/utils 8.55.0
│ │ └── ✕ unmet peer eslint@"^8.57.0 || ^9.0.0": found 10.0.0
│ ├─┬ @typescript-eslint/parser 8.55.0
│ │ └── ✕ unmet peer eslint@"^8.57.0 || ^9.0.0": found 10.0.0
│ └─┬ @typescript-eslint/eslint-plugin 8.55.0
│   ├── ✕ unmet peer eslint@"^8.57.0 || ^9.0.0": found 10.0.0

```

**Comment by NishargShah** [comment]
ESLint 10 released https://eslint.org/blog/2026/02/eslint-v10.0.0-released

**Comment by SukkaW** [comment]
@MirKml @melroy89 @NishargShah 

Technically, you can use `eslint-plugin-import-x` with ESLint 10 right now, as long as ~~you have either the `import-x/parsers` setting configured and~~ do not enable `import-x/no-unused-modules` rule.

~~Currently, we do not have a better alternative to `context.parserPath`, so omitting the `import-x/parsers` settings becomes impossible.~~ Update: you can still omit the `import-x/parsers` setting even with ESLint 10.

**Comment by NishargShah** [comment]
@SukkaW If possible can you add `v10` in the peers and make the release and inside that, you can mention to not use the `import-x/no-unused-modules` rule or you can create migration guidelines in the documentation.

https://github.com/un-ts/eslint-plugin-import-x/blob/a3aae6179f0a3417b46066dfe59b388865d1a2eb/package.json#L66

**Comment by MirKml** [comment]
@NishargShah I disagree. All mentioned changes by @SukkaW are breaking changes. So new major version is definitely needed if no replacement will be provided. It's up to SukkaW how he decide. 
I agree with drop both - `import-x/parsers` settings necessity isn't big deal, and `import-x/no-unused-modules` depends now on old config, isn't supported now by current standard eslint flat config [as mentioned in doc](https://github.com/un-ts/eslint-plugin-import-x/blob/master/docs/rules/no-unused-modules.md)

As I think, old config won't be possible with eslint 10+ either, also node requirements changed. So new major for this plugin is necessary.

**Comment by NishargShah** [comment]
@MirKml Makes sense. I support the best solution, one that’s permanent and future-proof.

**Comment by SukkaW** [comment]
cc @MirKml @NishargShah 

It is possible to retain the optional `import-x/parsers`. `eslint-plugin-import-x` is already extracting the parser from `context.languageOptions` when possible, so missing `context.parserPath` is not a huge deal. 

As for `import-x/no-unused-modules`, ESLint 10 finally removes `FileEnumerator` from `eslint/use-at-your-own-risk`, so this rule will break on ESLint 10, and there is no way we can fix this, at least for now.

As long as you don't use `import-x/no-unused-modules` and ignore peerDeps warning, you should be able to use `eslint-plugin-import-x` with ESLint 10.

**Comment by MirKml** [comment]
OK, it's up to you @SukkaW, I will definitely wait for new release with declared eslint 10 compatibility without any peerDeps workarounds/ignores etc. Hacking peerDeps compat with npm client (--force, --legacy-peer-deps ....) is problematic with side effects, error prone.

It's desired if you can align such new release with typescript-eslint plugin. because using this one and your plugin is common use case. It seems that they [finished compatibility](https://github.com/typescript-eslint/typescript-eslint/pull/12057) and new typescript-eslint plugin will be released soon.

**Comment by MirKml** [comment]
typescript-eslint with eslint 10 support [was released](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v8.56.0)

**Comment by SukkaW** [comment]
@MirKml 

We will be bumping our `@typescript-eslint/*` deps to the latest, and update our peerDeps ESLint version range **soon** (maybe after #457 ?). And then the `eslint-plugin-import-x` ESLint 10 support would be finished!

In the meantime, I have already landed #454, which also fixes a few crashes on ESLint 10.

**Comment by SukkaW** [comment]
Another update: #457 is growing way too big, so I have split most of its changes to another PR #458, and #457 is now only focusing on making `no-unused-modules` a no-op.

#458 focuses on including ESLint 10 in the CI testing matrix, and we will fix any issues surfaced in ESLint 10 testing.

**Comment by IanVS** [comment]
Just a small suggestion, but it might be worth pinning this issue, since now that ESLint 10 is released, others (like myself) may be looking for this issue to determine the status of support.

Thanks for working on making the plugin compatible!

**Comment by SukkaW** [comment]
Update: https://github.com/un-ts/eslint-plugin-import-x/pull/457 has been landed.

We are doing our final stretch, and we are getting there: https://github.com/un-ts/eslint-plugin-import-x/pull/458

- `@babel/eslint-parser@7` doesn't support ESLint 10, which means our test suite can't finish
  - `@babel/eslint-parser@8.0.0-rc2` does support ESLint 10, but it is ESM-only, which is not supported by Jest (Jest doesn't support `require(ESM)` even though Node.js itself does support it: https://github.com/jestjs/jest/issues/15275)
  - No, we can't switch to `jest-light-runner`. Already tried, faced other roadblocks like `jest.unstable_mockModule` not supported, and more.
  - No, `--experimental-vm-modules` does not help. We already added this about a year ago.
  - No, we won't migrate away from Jest, at least not for now
  - We have bundled `babel-eslint-parser-8-cjs` for now to test ESLint 10, which results in a few other issues, and we are still skipping test suites that crash.
- ~~`@angular-eslint/template-parser` doesn't support ESLint 10, which means our test suite can't finish~~
  - ~~https://github.com/angular-eslint/angular-eslint/issues/2896#issuecomment-3909840332~~
  - ~~The test is skipped for now~~
- `import typeof` flow syntax is no longer supported by ESLint 10 and the Babel ESLint parser (the parser just crashes)
  - Those flow syntax tests are being skipped for now

**Comment by MirKml** [comment]
Thanks for update - `@babel/eslint-parser` - Any mention - ticket, comment - about backport eslint 10 support to current - 7 version? Do they only recommend switch to 8.0.0 with ESM only and require(ESM)?
Jest with ESM -  ehh - big blocker everywhere. Jest - after some attempt to get back with major update last year - is in bad condition.

I think I use jest with only CJS because of ESM horrible situation - I use transform esm packages into cjs - but maybe with ... babel-jest :-) - we are back in babel. Uff Javascript open source ecosystem is in some situation very confusing and exhausted.

But as I understand - you skipping some tests and move forward  👍. Huge endurance.

**Comment by SukkaW** [comment]
Update since https://github.com/un-ts/eslint-plugin-import-x/issues/438#issuecomment-3993072922:

- Angular ESLint has fixed its ESLint 10 support, thus reducing one of our skipped tests.
- No, Flow `import typeof` is still broken on ESLint 10 + Babel parser combo.
- No, Babel has not backported its ESLint 10 support to Babel 7, and it is most likely they will never do.

**Comment by veith** [comment]
> Update since [#438 (comment)](https://github.com/un-ts/eslint-plugin-import-x/issues/438#issuecomment-3993072922):
> 
> * Angular ESLint has fixed its ESLint 10 support, thus reducing one of our skipped tests.
> * No, Flow `import typeof` is still broken on ESLint 10 + Babel parser combo.
> * No, Babel has not backported its ESLint 10 support to Babel 7, and it is most likely they will never do.

Does this mean, we will have a ESLint 10 compatible version soon?

**Comment by SukkaW** [comment]
> Does this mean, we will have a ESLint 10 compatible version soon?

@veith 

See https://github.com/un-ts/eslint-plugin-import-x/issues/438#issuecomment-3882662432

As I said before:

> As long as you don't use `import-x/no-unused-modules` rule, and ignore the peerDeps warning, you should be able to use `eslint-plugin-import-x` with ESLint 10 right now.

**Comment by silverwind** [comment]
Imho go for the breaking change:

- Migrate Jest to Vitest
- Drop Flow support

**Comment by SukkaW** [comment]
**Update**

We have merged #458, so `eslint-plugin-import-x` is now ESLint 10-ready.

Hooray? Not yet, but VERY SOON.

We'd like to include #466 (which fixes ESLint `defineConfig()` TypeScript support) in the new release as well. After #466 is merged, we will be dropping a new release.

**Comment by SukkaW** [comment]
**Update**: Both #466 and #407 have been merged, and the CI has released a newer version `4.16.2` with ESLint 10 included in the peer deps range.

Closing now.

**Comment by RobinBobin** [comment]
I'm still facing

```
ESLint removes the FileEnumerator API since ESLint 10, which is required by the "no-unused-modules" rule. Therefore, the "no-unused-modules" rule is no-op for now before we can implement an alternative.
In the meantime, if you want to keep this rule enabled, you can suppress this warning with the "suppressMissingFileEnumeratorAPIWarning" rule option: `import-x/no-unused-modules: ['error', { suppressMissingFileEnumeratorAPIWarning: true }]`
```

Relevant package versions:
```
"eslint": "^10.2.1",
"eslint-import-resolver-typescript": "^4.4.4",
"eslint-plugin-import-x": "^4.16.2",
```

Relevant parts of my `eslint.config.js`:

```
import eslintPluginImportX from 'eslint-plugin-import-x'

export default defineConfig([
{
    extends: ['import-x/flat/recommended', 'import-x/flat/typescript'],
    plugins: {
      'import-x': eslintPluginImportX
    },
    rules: {
      'import-x/no-unused-modules': [
        'error',
        {
          missingExports: true
        }
      ]
    }
}
```

**Comment by SukkaW** [comment]
> I'm still facing
> 
> ```
> ESLint removes the FileEnumerator API since ESLint 10, which is required by the "no-unused-modules" rule. Therefore, the "no-unused-modules" rule is no-op for now before we can implement an alternative.
> In the meantime, if you want to keep this rule enabled, you can suppress this warning with the "suppressMissingFileEnumeratorAPIWarning" rule option: `import-x/no-unused-modules: ['error', { suppressMissingFileEnumeratorAPIWarning: true }]`
> ```

This is intentional. This warning is doing exactly what is intended: warning you that this rule no longer works with ESLint 10, and we do not have any way to restore its functionality currently.

**Comment by RobinBobin** [comment]
> **Update**
> 
> We have merged #458, so `eslint-plugin-import-x` is now ESLint 10-ready.
> 
> Hooray? Not yet, but VERY SOON.
> 
> We'd like to include #466 (which fixes ESLint `defineConfig()` TypeScript support) in the new release as well. After #466 is merged, we will be dropping a new release.

Oh, I see. I misunderstood your message then 🙂🤷
https://github.com/un-ts/eslint-plugin-import-x/issues/438#issuecomment-4041612875
